"""empty message

Revision ID: 42693b5af75b
Revises: 
Create Date: 2020-08-13 20:18:05.700675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42693b5af75b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('upi_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_details_email'), 'user_details', ['email'], unique=True)
    op.create_index(op.f('ix_user_details_full_name'), 'user_details', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_details_password'), 'user_details', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_details_password'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_full_name'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_email'), table_name='user_details')
    op.drop_table('user_details')
    # ### end Alembic commands ###
