"""empty message

Revision ID: b854b9d428f8
Revises: d3a6963d9578
Create Date: 2020-08-17 21:01:54.485835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b854b9d428f8'
down_revision = 'd3a6963d9578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('upi_id', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_data_description'), 'payment_data', ['description'], unique=False)
    op.create_index(op.f('ix_payment_data_email'), 'payment_data', ['email'], unique=False)
    op.create_index(op.f('ix_payment_data_user_id'), 'payment_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_data_user_id'), table_name='payment_data')
    op.drop_index(op.f('ix_payment_data_email'), table_name='payment_data')
    op.drop_index(op.f('ix_payment_data_description'), table_name='payment_data')
    op.drop_table('payment_data')
    # ### end Alembic commands ###
