"""empty message

Revision ID: d3a6963d9578
Revises: ee6d741b4835
Create Date: 2020-08-17 20:57:22.364282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a6963d9578'
down_revision = 'ee6d741b4835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_data_description', table_name='payment_data')
    op.drop_index('ix_payment_data_email', table_name='payment_data')
    op.drop_index('ix_payment_data_user_id', table_name='payment_data')
    op.drop_table('payment_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upi_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payment_data_pkey')
    )
    op.create_index('ix_payment_data_user_id', 'payment_data', ['user_id'], unique=False)
    op.create_index('ix_payment_data_email', 'payment_data', ['email'], unique=False)
    op.create_index('ix_payment_data_description', 'payment_data', ['description'], unique=False)
    # ### end Alembic commands ###
